# -*- coding: utf-8 -*-
"""Build output/prospects-dashboard.html from data/applications.md + reports/ + prepped kits.
Self-contained: parse tracker (4.0+ actionable) -> enrich (tier/lane/cv/prepped/comp) -> write interactive HTML.
Run:  python scripts/build-dashboard.py
"""
import re, os, glob, json, sys, html as _html

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)
sys.path.insert(0, os.path.join(ROOT, 'scripts'))
import _candidate  # noqa: E402  (identity lives in config/profile.yml, never in code)
import _lane, _location  # noqa: E402  (lanes and the commute area are config too)
LOCATION = _location.load()
CANDIDATE = _candidate.load()

# Generated by comp-basis.mjs from score-model.mjs. Absent is fine -- the board then
# renders bare figures exactly as before rather than failing the build.
try:
    COMP_BASIS = json.load(open('data/comp-basis.json', encoding='utf-8'))
except Exception:
    COMP_BASIS = {}

kitfiles = {}  # basename -> lowercased content
for f in (glob.glob('output/*prep*.md') + glob.glob('output/*kit*.md') +
          glob.glob('output/*packet*.md') + glob.glob('output/*session*.md')):
    try:
        kitfiles[os.path.basename(f)] = open(f, encoding='utf-8').read().lower()
    except Exception:
        pass
kitblob = ''.join(kitfiles.values())
kit_wordcount = {fn: max(len(txt.split()), 1) for fn, txt in kitfiles.items()}

# canonical CV filenames actually on disk, keyed by a normalized form, so a loosely-worded
# in-doc mention ("Jane-Smith-AI-CV.pdf", "Jane-Smith-AI-CV", different case) all resolve
# to the one real file. The prefix is the candidate's name from config/profile.yml.
def _norm_cv(s):
    return re.sub(r'(pdf|html)$', '', re.sub(r'[^a-z0-9]', '', s.lower()))
_CV_SLUG = CANDIDATE['file_slug']
CV_FILES = sorted(os.path.basename(f) for f in glob.glob('output/%s-*-CV.pdf' % _CV_SLUG))
CV_CANON = {_norm_cv(f): f for f in CV_FILES}
CV_PATTERN = re.compile(re.escape(_CV_SLUG.lower()) + r'-[a-z-]+-cv(?:\.pdf|\.html)?', re.I)

# --- comp extraction ---------------------------------------------------------
# Reports were authored across many batches with drifting heading conventions, so a
# single "## Comp" match only catches ~half. Comp actually lives in one of:
#   1. a "## Comp" section          (early reports)
#   2. comp_posted: "..."           (Machine Summary YAML -- machine-authored, cleanest)
#   3. a "## ...Comp..." heading    ("Culture vs Comp", "Block D -- Compensation", "D) Comp & Demand")
# We try them in that order and normalize every hit to a compact "$174K-$253K" band.
# A guarded prose fallback (3) only trusts a range on a synthesis line so it never
# grabs the candidate's own target/floor figures (e.g. "target $X-YK, floor $ZK")
# as the role's pay.
_MONEY = r'\$?\s*[\d,.]+\s*[KkMm]?'
RANGE_RE = re.compile(r'\$\s*[\d,.]+\s*[KkMm]?\s*(?:-|–|—|to)\s*' + _MONEY)
# A $ range is the candidate's own number (target/floor/past comp), not the role's pay,
# when the text JUST BEFORE it says so. Checked on the ~35 chars preceding each range -- NOT the
# whole line -- so a downstream "AIP (~10-15% target)" bonus-target % never disqualifies a
# real posted band like "Verbatim: CA $211,800-$306,625 ... (~10-15% target)".
# The window is also clamped to the START OF THE LINE, because a blind 35-char lookback
# reaches back across the line break into the PREVIOUS sentence. That silently blanked
# one real posted band: the line is just "**Comp:** $310-520K", but the sentence above
# it ended "...isn't their kind of TA.", and that stray "their"
# disqualified the band (found 2026-07-30). Only text on the same line can qualify it.
#
# The candidate's first name and past employers join the cue list, since report prose
# introduces their own figures that way ("at Studio X she earned..."). Both come from
# config/profile.yml; an unconfigured clone simply has fewer cues.
_OWN_CUES = [r'target', r'floor', r'\bvs\b', r'\b(?:his|her|their|my)\b', r'step-?down',
             r'current', r'prior'] + \
            [r'\b%s\b' % re.escape(w) for w in
             [CANDIDATE['first_name']] + CANDIDATE['past_employers'] if w]
_OWN_PRE = re.compile('|'.join(_OWN_CUES), re.I)
# cue that a line states the evaluator's own total estimate (preferred over a raw market ref)
_SYNTH = re.compile(r'estimate|total comp|realistic|typical|lands? in|likely', re.I)

def _norm_k(tok):
    """'$174,000' / '$174K' / '$1.2M' -> '$174K' / '$1200K'. None if unparseable."""
    m = re.match(r'\$?\s*([\d,.]+)\s*([KkMm]?)', tok.strip())
    if not m:
        return None
    try:
        val = float(m.group(1).replace(',', ''))
    except ValueError:
        return None
    suf = m.group(2).lower()
    if suf == 'm':
        val *= 1000.0
    elif suf != 'k' and val >= 1000:   # bare full-dollar figure -> thousands
        val /= 1000.0
    return '$%dK' % round(val)

def _clean_ranges(text):
    """All well-formed $ ranges in text whose immediate preceding context is NOT about
    the candidate's own target/floor/past comp, normalized to '$LoK-$HiK', in document
    order."""
    out = []
    for m in RANGE_RE.finditer(text):
        line_start = text.rfind('\n', 0, m.start()) + 1
        if _OWN_PRE.search(text[max(line_start, m.start() - 35):m.start()]):
            continue
        parts = re.findall(_MONEY, m.group(0))
        if len(parts) >= 2:
            lo, hi = _norm_k(parts[0]), _norm_k(parts[-1])
            if lo and hi:
                out.append('%s-%s' % (lo, hi))
    return out

def _first_clean(text):
    r = _clean_ranges(text)
    if r:
        return r[0]
    return _single_ended(text)

# Some postings state one bound, not a range ("base up to $269,000", "$200K+"). RANGE_RE
# needs two figures, so those rendered BLANK -- which reads as "no comp data" when the
# number is right there. Show the bound with its direction rather than inventing a range.
_UP_TO = re.compile(r'\b(?:up to|max(?:imum)?(?: of)?|no more than)\s*(\$\s*[\d,.]+\s*[KkMm]?)', re.I)
_FROM = re.compile(r'\b(?:from|starting at|at least|min(?:imum)?(?: of)?)\s*(\$\s*[\d,.]+\s*[KkMm]?)', re.I)
_PLUS = re.compile(r'(\$\s*[\d,.]+\s*[KkMm]?)\s*\+')

def _single_ended(text):
    for line in text.splitlines():
        line_start = 0
        for rx, fmt in ((_UP_TO, '≤%s'), (_FROM, '%s+'), (_PLUS, '%s+')):
            m = rx.search(line)
            if not m:
                continue
            if _OWN_PRE.search(line[max(line_start, m.start() - 35):m.start()]):
                continue
            v = _norm_k(m.group(1))
            if v:
                return fmt % v
    return ''

# Some employers state TWO bands for ONE req in a single sentence, in the shape "the base
# salary range is $AK-$BK for Level 3, and $CK-$DK for Level 4." Taking only the first
# range reports the LOWER ladder and understates the role. When ONE LINE carries level
# markers and 2+ clean ranges, span them.
# Match ONLY the posting's own construction: a range IMMEDIATELY FOLLOWED by "for Level N".
# A looser "line mentions a level" test over-spans: it merged an unrelated comparator
# sentence, one that names a lower level's band while discussing a different req, into a
# fake spanned band for a posting that never stated one, and it likewise merged a posted
# band with a separate ESTIMATE figure that happened to share the line. Requiring the
# level marker to TRAIL the range excludes both, because in a comparator the level word
# leads instead.
_BAND_FOR_LEVEL = re.compile(
    r'(\$\s*[\d,.]+\s*[KkMm]?\s*(?:-|–|—|to)\s*\$?\s*[\d,.]+\s*[KkMm]?)'   # the range
    r'(?:\s*USD)?[\s*]{0,4}[(\[]?\s*(?:for\s+)?(?:level\s*\d|L[3-7])\b', re.I)

def _span_if_leveled(text):
    for line in text.splitlines():
        bands = [m.group(1) for m in _BAND_FOR_LEVEL.finditer(line)]
        if len(bands) < 2:
            continue
        lows, highs = [], []
        for b in bands:
            parts = re.findall(_MONEY, b)
            if len(parts) < 2:
                return ''
            lo, hi = _norm_k(parts[0]), _norm_k(parts[-1])
            if not lo or not hi:
                return ''
            lows.append(int(re.sub(r'[^\d]', '', lo)))
            highs.append(int(re.sub(r'[^\d]', '', hi)))
        return '$%dK-$%dK' % (min(lows), max(highs))
    return ''

def extract_comp(txt):
    # 0. a single line stating multiple LEVEL bands is the posted band and the most
    #    specific signal in the document -- span it before anything else.
    spanned = _span_if_leveled(txt)
    if spanned:
        return spanned
    # 1. explicit "## Comp" section (early reports)
    cs = re.search(r'## Comp\s*\n(.+?)(?:\n##|\Z)', txt, re.S)
    if cs:
        r = _first_clean(cs.group(1))
        if r:
            return r
    # 2. comp_posted from Machine Summary YAML -- machine-authored posted band, cleanest.
    #    If the value is explicitly flagged a market ESTIMATE (indie studios that publish
    #    no band), render it distinctly as "~$X-$Y est" so it's never mistaken for a posted
    #    band. Trigger only on the literal word "estimate" (no real posted band uses it).
    mp = re.search(r'comp_posted:\s*["\']?(.+)', txt)
    if mp:
        r = _first_clean(mp.group(1))
        if r:
            return '~%s est' % r if re.search(r'estimate', mp.group(1), re.I) else r
    # 3. any "## ...Comp..." heading section ("Culture vs Comp", "Block C -- Comp",
    #    "D) Comp & Demand"). Prefer a range on the evaluator's synthesis line; else the
    #    first clean range (usually the verbatim posted band).
    sections = []
    for hm in re.finditer(r'^##+\s*.*comp.*$', txt, re.I | re.M):
        start = hm.end()
        end = re.search(r'\n##', txt[start:])
        sections.append(txt[start:start + (end.start() if end else len(txt))])
    for sec in sections:
        for line in sec.splitlines():
            if _SYNTH.search(line):
                r = _first_clean(line)
                if r:
                    return r
    for sec in sections:
        r = _first_clean(sec)
        if r:
            return r
    # 4. floor-only fallback: union / CBA roles publish an HOURLY minimum ("no less than
    #    $62.74 an hour") instead of a salaried band. Annualize (x2080) and render as a
    #    floor "$131K+" so the row isn't blank. Lowest priority -- only when no real range
    #    exists anywhere, so it never overrides a posted band.
    hm = re.search(r'\$\s*(\d{1,3}(?:\.\d{1,2})?)\s*(?:/\s*hr|/\s*hour|\s*(?:an|per)\s+hour)', txt, re.I)
    if hm:
        try:
            annual = float(hm.group(1)) * 2080
            return '$%dK+' % round(annual / 1000)
        except ValueError:
            pass
    return ''

ACTIONABLE_FLOOR = 4.0   # the apply line
NEAR_MISS_FLOOR  = 3.8   # carried on the board, tagged, not counted as actionable

rows = []
# A fresh install has no tracker until the first evaluation is written; say so rather
# than end in a traceback.
if not os.path.exists('data/applications.md'):
    print('NOT BUILT: data/applications.md does not exist yet (evaluate an offer first)')
    sys.exit(0)
for ln in open('data/applications.md', encoding='utf-8'):
    if not ln.strip().startswith('|'):
        continue
    c = [x.strip() for x in ln.strip().strip('|').split('|')]
    if len(c) < 9 or not re.match(r'^\d+$', c[0]):
        continue
    m = re.match(r'([0-9.]+)', c[4]); sc = float(m.group(1)) if m else 0
    # Include near misses. The 2026-07-27 recompute moved 185 rows, so a role can now sit
    # at 3.8-3.9 having been above the line the day before, and six rows only reach 4.0 by
    # rounding to the tracker's single decimal place. A hard 4.0 cut hides all of that.
    # Near misses are carried but tagged, so the line stays visible instead of blurred.
    if not (sc >= NEAR_MISS_FLOOR and c[5] in ('Evaluated', 'Applied', 'Responded', 'Interview', 'Offer')):
        continue
    near_miss = sc < ACTIONABLE_FLOOR
    num, co, role, note, status = c[0], c[2], c[3], c[8], c[5]
    applied = status in ('Applied', 'Responded', 'Interview', 'Offer')
    comp, loc, url, report_txt = '', '', '', ''
    # Resolve the report via the row's OWN markdown link (col 7), not a glob by number:
    # report filenames drifted off-by-one from tracker row-numbers, so glob('reports/N-*')
    # matched a DIFFERENT job's report for ~49 rows (e.g. Mercury row read Calix's comp).
    # The link is authoritative (written by merge-tracker.mjs). Glob only as a last resort.
    rp = None
    lm = re.search(r'\]\(([^)]*reports/[^)]+)\)', c[7])
    if lm:
        cand = re.sub(r'^\.\./', '', lm.group(1))
        if os.path.isfile(cand):
            rp = cand
    if rp is None:
        g = sorted(glob.glob('reports/%03d-*.md' % int(num)))
        rp = g[0] if g else None
    if rp:
        txt = open(rp, encoding='utf-8').read()
        report_txt = txt
        ml = re.search(r'\*\*Location:\*\*\s*(.+)', txt)
        loc = ml.group(1).strip() if ml else ''
        if not loc:  # reports that use "## Block A -- Location" instead of a header line:
            lm2 = re.search(r'^location:\s*["\']?(.+)', txt, re.M)  # fall back to Machine Summary
            loc = lm2.group(1).strip().strip('"\'') if lm2 else ''
        comp = extract_comp(txt)
        # The model scores against a TOTAL-comp floor, but most postings publish a BASE band.
        # Showing one bare number conflates the two: a base-only band at an employer with no
        # IC cash bonus can straddle the floor while a same-looking total would clear it. Basis
        # comes from score-model.mjs via comp-basis.mjs -- the same classifier the scoring
        # model gates on -- never a second parser here.
        # Only label when the sidecar is provably describing THE SAME figure shown here:
        # compare its posted lo/hi against the rendered range. A basis derived from some
        # other number in the report (a total estimate, a comparable) must not be pinned
        # onto this one -- that mislabelled a base band as "total" on first attempt.
        cb = COMP_BASIS.get(num)
        if comp and cb:
            shown = [int(x) for x in re.findall(r'\$(\d+)K', comp)]
            same = (len(shown) == 2 and cb.get('posted_lo') and cb.get('posted_hi')
                    and abs(shown[0] - cb['posted_lo']) <= 1 and abs(shown[1] - cb['posted_hi']) <= 1)
            b = cb.get('posted_basis') if same else None
            comp += ' base' if b == 'base' else ' total' if b == 'total' else ' ?'
        mu = re.search(r'\*\*URL:\*\*\s*(\S+)', txt)
        if mu and mu.group(1).lower().startswith(('http://', 'https://')):
            url = mu.group(1)
    if not url:
        # fall back to a bare URL in the tracker note column
        mn = re.search(r'https?://\S+', note)
        if mn:
            url = mn.group(0).rstrip('.,)')
    # The page shows 150 characters of the location; the tier reads all of it, or a commute
    # city named late in a long line ("... or Culver City, CA") never reaches tier().
    rows.append(dict(num=num, sc=sc, co=co, role=role, note=note, comp=comp, loc=loc[:150], url=url,
                      status=status, applied=applied, near_miss=near_miss, _report_txt=report_txt,
                      _loc_full=loc))

_PREFS = _candidate.load_prefs()

def star(co):
    # Marker from config/profile.yml company_preference; no list of employers in code.
    return _candidate.pref_mark(co, _PREFS)

def lane(role):
    # Lane buckets and the CV each suggests are the preset's `_board` section
    # (config/lane-vocab.json); the dashboard only renders them.
    return _lane.board_lane(role)[0]

def cv(ln):
    for entry in _lane.section("_board").get("lanes", []):
        if entry["name"] == ln:
            return entry.get("cv", "")
    return (_lane.section("_board").get("fallback") or {}).get("cv", "")

def lane_buttons(active_first=False):
    """Filter buttons for the lanes the preset marks with a `button` label, in order."""
    seen, out = set(), []
    for ln in _lane.section("_board").get("lanes", []):
        if ln.get("button") and ln["name"] not in seen:
            seen.add(ln["name"])
            out.append('<span class="btn" data-lane="%s">%s</span>'
                       % (_html.escape(ln["name"], quote=True), _html.escape(ln["button"])))
    return "\n".join(out)

# The tier a row lands in when its location is inside the commute area. The area and its
# label come from config/location.json (see presets/locations/).
COMMUTE = 'Commute'
_ONSITE = ['(onsite)', 'onsite', 'on-site', 'on site', 'in-person', 'in person', '5-day', '5 day', 'hybrid']

def tier(co, role, loc, note):
    """Derive the location tier from LOCATION TEXT only. A company name is never evidence:
    one employer can post an LA-onsite role and a remote one in the same week, so a name
    must never override an explicit listing. Rows the text cannot place read 'Check'."""
    t = (loc + ' ' + note).lower()

    # 1. Explicit eval-assigned **[tag]** wins (most authoritative human signal)
    m = re.search(r'\*\*\[([^\]]+)\]\*\*', loc + ' ' + note)
    if m:
        tag = m.group(1).lower()
        if ('onsite' in tag or 'hybrid' in tag or 'commute' in tag
                or LOCATION.commute_label.lower() in tag): return COMMUTE
        if 'negoti' in tag or 'gated' in tag or 'confirm' in tag: return 'Negotiation-gated'
        if 'remote' in tag: return 'Remote-US'

    onsite = any(w in t for w in _ONSITE)
    # The commute area is read from the LOCATION only, never the note prose: a note
    # saying "no SoCal office" is about the commute area without being in it.
    socal = LOCATION.in_commute_area(loc)
    remote_ok = ('remote' in t) and not any(neg in t for neg in ['not remote', 'no remote', "isn't remote", 'not fully remote'])

    # 2. Location text decides. Explicit onsite language forces a commute classification even
    #    for a company that CAN be remote (the Netflix-LA-onsite bug); a remote offer with an
    #    optional/preferred SoCal office is still Remote-US.
    if onsite:
        if socal: return COMMUTE
        if remote_ok: return 'Remote-US'   # onsite outside the commute OR remote (e.g. "onsite NYC or remote")
        return 'Check'
    if remote_ok: return 'Remote-US'
    if socal: return COMMUTE

    # 3. Negotiation signals
    if ('confirm ca-remote' in t or 'confirm remote' in t or 'location-gated' in t
            or 'negotiat' in t): return 'Negotiation-gated'
    return 'Check'

# The candidate's own bio recurs in nearly EVERY packet regardless of target company, so
# generic job-level and function words are useless discriminators: a word from the
# candidate's own specialty can appear in most packet files. Prefer words that are
# actually RARE across the corpus.
GENERIC_ROLE_WORDS = {
    'senior', 'staff', 'principal', 'lead', 'software', 'engineer', 'engineering',
    'technical', 'technology', 'manager', 'director', 'specialist', 'artist',
    'scientist', 'architect', 'applied', 'developer', 'systems', 'platform',
}

def _role_keywords(role):
    """Return (rl, require_match): the word-list used to judge whether a document is
    substantively ABOUT this role, preferring rare/corpus-distinctive words over generic
    job-level ones. Shared by prepped_file() (pick the packet) and find_cv() (pick the
    right CV mention inside a multi-role packet via proximity to these same words)."""
    all_words = [w for w in re.findall(r'[a-z]+', role.lower()) if len(w) > 4]
    specific = [w for w in all_words if w not in GENERIC_ROLE_WORDS]
    rare = [w for w in specific if role_word_docfreq.get(w, 0) <= 0.4 * max(len(kitfiles), 1)]
    rl = rare or specific or all_words  # degrade gracefully if the role has no rare/specific word
    require_match = bool(rare or specific)  # only demand a hit when we have a real signal to check
    # When NO rare word exists, every remaining keyword is corpus-common -- i.e. it is the
    # candidate's own bio, not this role. A title that reduces to one word from the
    # candidate's own history matches most packets for that reason alone. Falling back to
    # those words silently defeats the docfreq filter and lets a bio echo count as a role
    # match. Callers use has_rare to demand stronger corroboration.
    has_rare = bool(rare)
    return rl, require_match, has_rare

def prepped_file(co, role):
    """Return the packet/prep filename that best matches this role, or None.
    A file must substantively mention BOTH the company (>=2x AND not dwarfed by
    some OTHER tracked company's mention count in the same file -- e.g. a past employer
    said 8x as background bio inside a packet where the target appears 44x should NOT
    count as a packet for the past employer) and the role. The role match prefers RARE,
    corpus-distinctive keywords (e.g. "omniverse", "firefly") over generic
    job-level words that appear in nearly every packet via the candidate's recurring bio
    (e.g. "engineer", "rigging") -- see GENERIC_ROLE_WORDS + role_word_docfreq.
    Role-match strength is measured as DENSITY (hits per 1000 words), not a raw
    count -- otherwise a giant multi-company batch file always "wins" on volume
    alone against a short, focused, dedicated packet just because it's longer.
    Among qualifying files, prefer the most RECENT (by filename date) -- this
    project's convention is that later files (v2, "session", "packet") supersede
    earlier drafts, not that the highest raw mention-count wins."""
    cl = co.lower().split()[0]
    rl, require_match, has_rare = _role_keywords(role)
    candidates = []
    for fn, txt in kitfiles.items():
        co_count = txt.count(cl)
        if co_count < 2:
            continue
        # A company from the candidate's OWN WORK HISTORY appears as background bio in
        # nearly every packet, so a raw share threshold is not enough: a past employer hit
        # ~30% of the target inside one apply-session packet and mis-attached that packet to
        # an unrelated req at the past employer (found 2026-08-03). A file is only ABOUT a company if
        # either the FILENAME names it (the convention here: acme-*, globex-*) or
        # the company is a dominant subject of a genuinely multi-company file, not a 30% echo.
        named_in_filename = cl in fn.lower()
        if not named_in_filename and co_count < max(2, 0.6 * file_max_co_count.get(fn, 0)):
            continue  # incidental / bio mention -> not a packet for this company
        # No rare role word means the only thing we can match on is bio vocabulary. That is
        # not evidence a general prep session covers THIS req, so require the filename to
        # name the company before attributing. A dedicated acme-* packet is still
        # safe to attribute on a weak role word; a 15k-word multi-company batch file is not.
        if not has_rare and not named_in_filename:
            continue
        role_count = sum(txt.count(w) for w in rl) if rl else 0
        if require_match and role_count == 0:
            continue
        density = role_count / kit_wordcount.get(fn, 1) * 1000
        dm = re.search(r'(\d{4}-\d{2}-\d{2})', fn)
        vm = re.search(r'-v(\d+)-', fn)  # explicit revision marker: "...-v2-<date>.md" supersedes "...-<date>.md"
        candidates.append((int(vm.group(1)) if vm else 1, round(density, 3), dm.group(1) if dm else '', co_count, fn))
    if not candidates:
        return None
    # version FIRST (an explicit "-v2-" always supersedes "-v1-" of the same doc, even if
    # the revision has fewer incidental keyword hits); THEN role-match density (this is
    # what actually distinguishes two unrelated documents that both mention the company --
    # a short dedicated packet mentioning the role 18x in 700 words is a much stronger
    # match than a 300-hit mention buried in an 18,000-word multi-company batch file);
    # date/company-count are only a final tiebreak.
    candidates.sort(reverse=True)
    return candidates[0][4]

# A packet's opening "Resume:" note is often CONDITIONAL guidance covering every role in
# the file, e.g. "Resume: Jane-Smith-TA-CV.pdf (craft roles); AI-led CV variant better
# for AI/FDE/enablement ones." Proximity cannot parse that, so it handed the craft half to
# 8 roles including a Netflix agent-platform req (found 2026-07-30). Such a line names no
# single role's CV, so it must not count as an explicit mention -- better to fall through to
# the lane guess, which the caller labels as unconfirmed, than to assert a wrong CV.
_CV_HEDGE = re.compile(
    r'craft roles|better for|variant|instead|unless|override|general|'
    r'\bfor (?:ai|craft|the ai|these)\b|\bor\b.*\bcv\b|all (?:of them|five|4|5)', re.I)

def _is_conditional_cv_line(text, match):
    ls = text.rfind('\n', 0, match.start()) + 1
    le = text.find('\n', match.end())
    line = text[ls:le if le != -1 else len(text)]
    return len(CV_PATTERN.findall(line)) > 1 or bool(_CV_HEDGE.search(line))

def find_cv(role, report_txt, packet_fn):
    """Return (cv_filename, confirmed: bool). Looks for an EXPLICIT "<Name>-*-CV"
    mention -- never a guess when one exists on record:
      1. The per-role report (unambiguous -- one report, one role) always wins if it
         names a CV.
      2. Otherwise scan the matched packet file. Packets often cover MULTIPLE roles
         (batch/kit/session docs), so a global "first CV mentioned" search can grab the
         wrong one -- instead pick whichever CV mention sits CLOSEST to an occurrence of
         this role's own distinctive keyword (same rl word-list prepped_file() used to
         pick the packet in the first place).
    Returns (None, False) if no explicit mention exists anywhere -- caller should fall
    back to the coarse lane-based guess and say so, not present it as fact."""
    for txt in (report_txt or '',):
        if txt:
            m = CV_PATTERN.search(txt)
            if m:
                cv = CV_CANON.get(_norm_cv(m.group(0)))
                if cv:
                    return cv, True
    if not packet_fn or packet_fn not in kitfiles:
        return None, False
    ptxt = kitfiles[packet_fn]  # already lowercased
    cv_matches = [m for m in CV_PATTERN.finditer(ptxt) if not _is_conditional_cv_line(ptxt, m)]
    if not cv_matches:
        return None, False
    if len(cv_matches) == 1:
        cv = CV_CANON.get(_norm_cv(cv_matches[0].group(0)))
        return (cv, True) if cv else (None, False)
    rl, _, _ = _role_keywords(role)
    kw_positions = [m.start() for w in rl for m in re.finditer(re.escape(w), ptxt)]
    if not kw_positions:
        # can't disambiguate which of several CV mentions is "ours" -> don't guess
        return None, False
    best_cv, best_dist = None, None
    for m in cv_matches:
        dist = min(abs(m.start() - p) for p in kw_positions)
        if best_dist is None or dist < best_dist:
            cv = CV_CANON.get(_norm_cv(m.group(0)))
            if cv:
                best_cv, best_dist = cv, dist
    return (best_cv, True) if best_cv else (None, False)

# precompute, per packet file, the highest mention-count any TRACKED company reaches
# in it -- lets prepped_file() reject a company that's merely name-dropped (bio/background)
# in what is really some OTHER company's packet.
_company_keywords = sorted(set(r['co'].lower().split()[0] for r in rows))
file_max_co_count = {fn: max((txt.count(k) for k in _company_keywords), default=0)
                      for fn, txt in kitfiles.items()}

# precompute how many packet files each candidate role-word appears in at all (document
# frequency) -- words near-universal across the corpus (the recurring bio) are useless
# for telling packets apart; prepped_file() prefers rare ones instead.
_role_words = set()
for r in rows:
    _role_words.update(w for w in re.findall(r'[a-z]+', r['role'].lower()) if len(w) > 4)
role_word_docfreq = {w: sum(1 for txt in kitfiles.values() if w in txt) for w in _role_words}

for r in rows:
    r['star'] = star(r['co']); r['lane'] = lane(r['role'])
    r['tier'] = tier(r['co'], r['role'], r.pop('_loc_full'), r['note'])
    pf = prepped_file(r['co'], r['role'])
    r['prep'] = bool(pf); r['prepFile'] = pf or ''
    cv_confirmed, is_confirmed = find_cv(r['role'], r.pop('_report_txt', ''), pf)
    r['cv'] = cv_confirmed if is_confirmed else cv(r['lane'])
    r['cvConfirmed'] = is_confirmed
    r['gate'] = re.sub(r'\s+', ' ', r['note'])[:170]
rows.sort(key=lambda r: (-r['sc'], r['co']))

import datetime  # noqa  (only for label; not used for logic)
TPL_PATH = os.path.join('scripts', '_dashboard_template.html')
TPL = open(TPL_PATH, encoding='utf-8').read()
out = (TPL.replace('__DATA__', json.dumps(rows, ensure_ascii=False))
          .replace('__CANDIDATE__', _html.escape(CANDIDATE['full_name']))
          .replace('__LANE_BUTTONS__', lane_buttons())
          .replace('__COMMUTE_LABEL__', _html.escape(LOCATION.commute_label + ' commute'))
          .replace('__TOTAL__', str(len(rows)))
          .replace('__ACTIONABLE__', str(sum(1 for r in rows if not r['near_miss'])))
          .replace('__NEARMISS__', str(sum(1 for r in rows if r['near_miss'])))
          .replace('__PREPPED__', str(sum(1 for r in rows if r['prep'])))
          .replace('__DATE__', datetime.datetime.now().strftime('%b %d, %Y at %I:%M %p').replace(' 0', ' ')))
open('output/prospects-dashboard.html', 'w', encoding='utf-8').write(out)
print('wrote output/prospects-dashboard.html  (%d actionable + %d near miss, %d prepped, %d CVs confirmed from source)' %
      (sum(1 for r in rows if not r['near_miss']), sum(1 for r in rows if r['near_miss']),
       sum(1 for r in rows if r['prep']), sum(1 for r in rows if r['cvConfirmed'])))
